add revenuecoin staking
abridged/collabland-staking-contracts pull request #235
Opened 2024-05-22 15:40 UTC by fkrevenue

2024-05-29 01:41 UTC, alokt approved these changes

2024-05-29 01:44 UTC, alokt requested changes
can you please resolve this https://github.com/abridged/collabland-staking-contracts/pull/235/checks?check_run_id=25287589268

2024-06-13 14:28 UTC, fkrevenue commented
should be signed off correctly now

2024-07-02 05:25 UTC, alokt approved these changes

2024-07-02 05:26 UTC, merged

2024-07-02 05:32 UTC, alokt commented
@fkrevenue do you have url for this env var `RENFT_POLYGON_SYLVESTER_V1_SUBGRAPH_URL` ?  default subgraph https://api.thegraph.com/subgraphs/name/re-nft/sylvester-v1-polygon-main url is not working, plz lmk.